package com.h.mynote.greendao.greenBean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.io.Serializable;

/**
 * Entity mapped to table "NEWS_CATE".
 */
public class NewsCate implements Serializable {

    private Long id;
    private String name;
    private String value;
    private String isSel;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public NewsCate() {
    }

    public NewsCate(Long id) {
        this.id = id;
    }

    public NewsCate(Long id, String name, String value, String isSel) {
        this.id = id;
        this.name = name;
        this.value = value;
        this.isSel = isSel;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getIsSel() {
        return isSel;
    }

    public void setIsSel(String isSel) {
        this.isSel = isSel;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
